### ISSUE TITLE
Test simpleheatmap3 with missing values

### ISSUE THREAD

**Issue by wolski** [protViz/quantable#10]
heatmap3 fails when missing value. Develop strategy (i.e. remove rows) if this is the case.

**Comment by LucasKookUZH** [comment]
[This commit](https://github.com/LucasKookUZH/SRMService/commit/ccdd0065f924d36f778aa521fdccbfa5350796c1) adds a feature which uses only proteins that have been quantified in over 50% of the samples for clustering and subsequently merges the clusterIDs with the output from `.self$getResultTableWithPseudo()` using `full_join()` thus introducing `NA`s for proteins that have not been clustered.
