### ISSUE TITLE
Visualize clustering results in heatmap

### ISSUE THREAD

**Issue by wolski** [protViz/quantable#11]
Add cluster information to heatmap .
One option - use Row or ColSideColors.

**Comment by LucasKookUZH** [comment]
Adding this feature would require the clustering to be calculated before calling the `heatmap3()` function and would thus double computation time. Simpler solution would be to call `simpleheatmap3()` two times. First using `plot=FALSE` and second using `plot=TRUE` together with `ColSideColors = data$ClusterID`.

**Comment by LucasKookUZH** [comment]
[Here](https://github.com/LucasKookUZH/SRMService/commit/ccdd0065f924d36f778aa521fdccbfa5350796c1) I implemented the above mentioned idea in `Grp2AnalysisHeatmap3.Rmd` (lines 271-294) for an arbitrary number of clusters.

**Comment by LucasKookUZH** [comment]
[Now](url
https://github.com/LucasKookUZH/quantable/commit/152b58cbec5cc5c8a076d151ca12a2eaf7ecf1b4) column side colors are implemented per default in `simpleheatmap3.R`. Additionally an option was added to suppress this default coloring, which is used in `SRMService/vignettes/Grp2AnalysisHeatmap3.Rmd` to suppress column side coloring in the spearman-correlation matrix.
