### ISSUE TITLE
using factors in caret::confusionMatrix

### ISSUE THREAD

**Issue by topepo** [protViz/quantable#5]
The version of caret being sent to CRAN (6.0-79) has a change that affects your package. The details are here: 

   https://github.com/topepo/caret/commit/e4dc43d679f25f7289b835c29dfbae1527c7f880 

In summary, when creating a confusion matrix using two vectors, the input data are now required to be factors with the same levels. If this is an issue, you can get around it by creating a table and using `confusionMatrix.table` to get around the requirement.   

The issues for your respective packages are shown below. When you submit to CRAN, please make sure that the dependency has `caret (>= 6.0-79)`.  

Let me know if you have any questions.  

Thanks, 

Max 

```
    ...
    
    > ### Name: determineCut
    > ### Title: determine best Accuracy cuttoff
    > ### Aliases: determineCut
    > 
    > ### ** Examples
    > 
    > library(pROC)
    Type 'citation("pROC")' for a citation.
    
    Attaching package: ‘pROC’
    
    The following objects are masked from ‘package:stats’:
    
        cov, smooth, var
    
    > cases <- rnorm(100,-1,1.1)
    > controls <- rnorm(500,1,1.1)
    > cut <- determineCut(cases,controls)
    Error: `data` and `reference` should be factors with the same levels.
    Execution halted
 ```

**Comment by wolski** [comment]
Fixed
